name: Deploy Blazor WebAssembly to GitHub Pages

on:
  push:
    branches:
      - master # Replace with your default branch if not `main`
  workflow_dispatch: # Add this to enable manual triggering

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v3

    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: '9.0' # Adjust to match your project's target framework

    - name: Build Project
      run: dotnet publish -c Release -o build/publish

    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v4
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: build/publish/wwwroot
